### ISSUE TITLE
HTTPS Client Certificates

### ISSUE THREAD

**Issue by ericvw** [bloomberg/blpapi-http#13]
This issue is to investigate and implement the usage of HTTPS client certificates as a means of authentication and identity management.

Some investigative questions to answer are:
- Do we have access to the underlying certificate information?
  - If so, what part of the certificate can we use to uniquely identify the user?
- How does revocation lists of certificates work with the http server?

Please feel free to add any other investigative questions, answers, and progress.

**Comment by ericlu88** [comment]
Progress so far regarding getting access to underlying client cert info:

Getting access to the client cert in node is relatively easy. One just has to call `req.connection.getPeerCertificate()`, as noted in the [Node API doc](http://nodejs.org/api/http.html):

> With HTTPS support, use request.connection.verifyPeer() and request.connection.getPeerCertificate() > to obtain the client's authentication details.

The problem comes in when we try to do this in typescript. `req.connection` is type `net.Socket` when req is a **HTTP** request, and type `tls.ClearTextStream` when req is a **HTTPS** request. In order to get variant type notation in typescript, I upgrade the typescript compiler to 1.4.0 so that we could use **union** type(`req.connection: net.Socket|tls.ClearTextStream`). 

Within the extracted client certificate object, there's the **fingerprint** property that we could use to unique identify the user. I will start modifying the subscription code based on it.

**Comment by tmikov** [comment]
You can always do a typecast in typescript.

I am more curious about how to invalidate a client certificate?

**Comment by ericlu88** [comment]
Typecasting would only work in up/down casting, as explained in this [post](http://blogs.microsoft.co.il/gilf/2013/01/18/using-casting-in-typescript/). In this case, if the type annotation is `req.connection: net.Socket`, I get the following error when I try to cast it to `tls.ClearTextStream`:

> error TS2352: Neither type 'Socket' nor type 'ClearTextStream' is assignable to the other.
> Property 'authorized' is missing in type 'Socket'.

I will look into the client cert invalidation tomorrow.

**Comment by tmikov** [comment]
I don't have time to read the link, but you can totally cast anything into anything.
var x : Cls1;
var y : Cls2;
y = <Cls2><any>x;

**Comment by tmikov** [comment]
Stupid Github doesn't display < and > :-)

**Comment by ericlu88** [comment]
I've tried the following example and it doesn't seem to work:

```
interface Dog {
    woo(): void;
}

interface Cat {
    meow(): void;
}

var d: Dog;
var c: Cat;

d.woo();    // OK
c.meow();   // OK
d = <Dog>c; // Error
(<Dog>c).woo(); // Error

// error TS2353: Neither type 'Cat' nor type 'Dog' is assignable to the other:
// Property 'woo' is missing in type 'Cat'.
```

**Comment by tmikov** [comment]
As I said earlier, you need to type: <Dog><any>c;

**Comment by ericlu88** [comment]
Oh sorry I missed the double casting syntax. I tried and it did work. Thanks for the suggestion.

**Comment by ericlu88** [comment]
For certificate revocation list, node js support it by passing the following option when create the server:

```
crl : Either a string or list of strings of PEM encoded CRLs (Certificate Revocation List)
```

The followup problem is when the crl get updated, node doesn't seem to reload the file unless you restart the server. Also, node doesn't seem to have native support of _CRL Distribution Point_, where the server will periodically download the CRL from the specified URL to check whether any certificates have been revoked. 

Some ref:
- https://jamielinux.com/articles/2013/08/generate-certificate-revocation-list-revoke-certificates/
- http://nodejs.org/api/tls.html

**Comment by ericvw** [comment]
We have been using HTTPS client certificates for quite some time now - closing.
