### ISSUE TITLE
Add long-poll example for subscription(node.js)

### ISSUE THREAD

**Issue by ericlu88** [bloomberg/blpapi-http#76]
We need an example for long-polling subscription using `node.js`

**Comment by ericlu88** [comment]
When writing examples, is it best practice try not to use 3rd party libraries or it is fine? It would be much harder to write a long-polling example without `request`, `lodash` and `promise`.

**Comment by yupinghu** [comment]
As a principle, we should definitely be mindful of making it easy for people to run the examples with minimal extra software installed. At most we should only use things we're otherwise using in the project, but as much as possible we should even consider using less. In the cases you mention I think it's fine if needed.

I think in the case of node.js examples, anything that's easily npm installed is fine imo. For now, I think you can write the examples the way you'd like initially, and during review we'll consider if we can reduce the dependencies. Make sense?

**Comment by ericlu88** [comment]
Closed.
